#cloud-config

#/*******************************************************************************
# * Copyright (c) 2022 Achim Kraus, cloudcoap.net.
# * 
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * and Eclipse Distribution License v1.0 which accompany this distribution.
# * 
# * The Eclipse Public License is available at
# *    http://www.eclipse.org/legal/epl-v20.html
# * and the Eclipse Distribution License is available at
# *    http://www.eclipse.org/org/documents/edl-v10.html.
# ******************************************************************************/

package_upgrade: true

packages:
 - openjdk-17-jre-headless
 - fail2ban
 - vnstat

disable_root: false

users:
 - name: user
   gecos: Benchmark user
   shell: /bin/bash
   groups: users
   lock_passwd: true
   ssh_authorized_keys:
    - ssh-ed25519 ???????????????????????????????????????????????????????????????????? ???@???
# insert your ssh key above
